Src/InventoryManager.WebUI/Controllers/CategoryController.cs
using InventoryManager.Application.Interfaces.IServices;
using InventoryManager.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManager.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private const int pageSize = 1;
        private const bool pagination = true;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Index(string? searchTerm,int page=1,bool desc=false)
        {
            AssignToViewBag(searchTerm, page,desc);
            var categories=_categoryService.GetAllCategories(searchTerm,page:page,pageSize:pageSize,pagination:pagination,descending:desc);

            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.AddCategory(category);

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var category = _categoryService.GetCategoryById(id);

            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.UpdateCategory(category);

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var category = _categoryService.GetCategoryById(id);

            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.RemoveCategory(category);

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        public void AssignToViewBag(string? searchTerm, int page, bool desc = false)
        {
            ViewBag.SearchTerm = searchTerm;
            ViewBag.Desc = desc;
            ViewBag.CurrentPage = page;
            ViewBag.TotalPage = _categoryService.TotalPages(searchTerm, pageSize: pageSize);
            (ViewBag.StartPage, ViewBag.EndPage) = _categoryService.GetStartAndEnd(searchTerm, page,pageSize);

        }
    }
}

Src/InventoryManager.WebUI/Controllers/CustomerController.cs
using InventoryManager.Application.Interfaces.IServices;
using InventoryManager.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManager.WebUI.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;
        private const bool pagination = true;
        private const int pageSize = 1;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }
        public IActionResult Index(string? searchTerm,int page=1,bool desc=false)
        {
            AssignToViewBag(searchTerm, page,desc);
            var customers=_customerService.GetAllCustomers(searchTerm,page:page,pageSize:pageSize, pagination: pagination,descending:desc);

            return View(customers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _customerService.AddCustomer(customer);

                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var customer = _customerService.GetCustomerById(id);

            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _customerService.UpdateCustomer(customer);

                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var customer = _customerService.GetCustomerById(id);

            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _customerService.RemoveCustomer(customer);

                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }
        public void AssignToViewBag(string? searchTerm, int page, bool desc = false)
        {
            ViewBag.SearchTerm = searchTerm;
            ViewBag.Desc = desc;
            ViewBag.CurrentPage = page;
            ViewBag.TotalPage = _customerService.TotalPages(searchTerm, pageSize: pageSize);
            (ViewBag.StartPage, ViewBag.EndPage) = _customerService.GetStartAndEnd(searchTerm, page,pageSize);

        }
    }
}

Src/InventoryManager.WebUI/Controllers/ProductController.cs
using InventoryManager.Application.Interfaces.IServices;
using InventoryManager.Domain.Entities;
using InventoryManager.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManager.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private const bool pagination=true;
        private const int pageSize = 1;
        private readonly IWebHostEnvironment _env;

        public ProductController(IProductService productService, IWebHostEnvironment env)
        {
            _productService = productService;
            _env = env;
        }
        public IActionResult Index(string? searchTerm,int page=1,bool desc=false)
        {
            AssignToViewBag(searchTerm, page,desc);
            var products=_productService.GetAllProducts(searchTerm,page:page,pageSize:pageSize, pagination: pagination, descending:desc);

            return View(products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            (ViewBag.CategoryList,ViewBag.UnitList)=_productService.GetCategoryAndUnit();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                var product = GetProductFromVM(productVM);

                _productService.AddProduct(product);

                return RedirectToAction(nameof(Index));
            }

            (ViewBag.CategoryList, ViewBag.UnitList) = _productService.GetCategoryAndUnit();
            return View(productVM);
        }



        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var product = _productService.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }
            (ViewBag.CategoryList, ViewBag.UnitList) = _productService.GetCategoryAndUnit();
            return View(SetVMFromProduct(product));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductVM productVM)
        {
            if (ModelState.IsValid)
            {
                if (productVM.Product.ImagePath != null && productVM.ImageUri?.Length > 0)
                {
                    _productService.DeleteImage(productVM.Product.ImagePath,_env.WebRootPath);
                }
                
                var product = GetProductFromVM(productVM);
                product.Id = productVM.Product.Id;

                _productService.UpdateProduct(product);

                return RedirectToAction(nameof(Index));
            }
            (ViewBag.CategoryList, ViewBag.UnitList) = _productService.GetCategoryAndUnit();
            return View(productVM);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var product = _productService.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.ImagePath != null)
                {
                    _productService.DeleteImage(product.ImagePath, _env.WebRootPath);
                }
                _productService.RemoveProduct(product);

                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }


        [HttpGet]
        public IActionResult Details(int? id)
        {
            var product = _productService.GetProductById(id,"Category,Unit");

            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }



        public void AssignToViewBag(string? searchTerm, int page, bool desc = false)
        {
            ViewBag.SearchTerm = searchTerm;
            ViewBag.Desc = desc;
            ViewBag.CurrentPage = page;
            ViewBag.TotalPage = _productService.TotalPages(searchTerm, pageSize: pageSize);
            (ViewBag.StartPage, ViewBag.EndPage) = _productService.GetStartAndEnd(searchTerm, page,pageSize);

        }
        Product GetProductFromVM(ProductVM productVM)
        {
            var imagePath = _productService.ImagePath(productVM.ImageUri, _env.WebRootPath);
            return new Product
            {

                Name = productVM.Product.Name,
                Description = productVM.Product.Description,
                Price = productVM.Product.Price,
                CategoryId = productVM.Product.CategoryId,
                UnitId = productVM.Product.UnitId,
                ImagePath = imagePath,
            };
        }
        ProductVM SetVMFromProduct(Product product)
        {
            return new ProductVM
            {
                Product = product
            };
        }
    }
}

Src/InventoryManager.WebUI/Controllers/UnitController.cs
using InventoryManager.Application.Interfaces.IServices;
using InventoryManager.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManager.WebUI.Controllers
{
    public class UnitController : Controller
    {
        private readonly IUnitService _unitService;
        private const bool pagination = true;
        private const int pageSize = 1;

        public UnitController(IUnitService unitService)
        {
            _unitService = unitService;
        }
        public IActionResult Index(string? searchTerm,int page=1,bool desc=false)
        {
            AssignToViewBag(searchTerm, page,desc);
            var units=_unitService.GetAllUnits(searchTerm,page:page,pageSize:pageSize, pagination: pagination,descending:desc);

            return View(units);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Unit unit)
        {
            if (ModelState.IsValid)
            {
                _unitService.AddUnit(unit);

                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var unit = _unitService.GetUnitById(id);

            if (unit == null)
            {
                return NotFound();
            }
            return View(unit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Unit unit)
        {
            if (ModelState.IsValid)
            {
                _unitService.UpdateUnit(unit);

                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var unit = _unitService.GetUnitById(id);

            if (unit == null)
            {
                return NotFound();
            }
            return View(unit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Unit unit)
        {
            if (ModelState.IsValid)
            {
                _unitService.RemoveUnit(unit);

                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }
        public void AssignToViewBag(string? searchTerm, int page, bool desc = false)
        {
            ViewBag.SearchTerm = searchTerm;
            ViewBag.Desc = desc;
            ViewBag.CurrentPage = page;
            ViewBag.TotalPage = _unitService.TotalPages(searchTerm, pageSize: pageSize);
            (ViewBag.StartPage, ViewBag.EndPage) = _unitService.GetStartAndEnd(searchTerm, page,pageSize);

        }
    }
}

Src/InventoryManager.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryManager.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryManager.WebUI.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet" />

    @RenderSection("Styles", required: false)

    <style>
        body {
            background: linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%);
            min-height: 100vh;
            color: #fff;
        }

        .navbar-green {
            background: linear-gradient(135deg, #0f2027, #203a43) !important;
            border-bottom: 2px solid rgba(0, 212, 170, 0.3);
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
        }

            .navbar-green .navbar-brand,
            .navbar-green .nav-link,
            .navbar-green .dropdown-toggle {
                color: #fff !important;
                transition: all 0.3s ease;
            }

            .navbar-green .navbar-brand {
                background: linear-gradient(45deg, #00f5ff, #00d4aa);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
                font-weight: 700;
            }

            .navbar-green .nav-link:hover,
            .navbar-green .dropdown-toggle:hover {
                background: linear-gradient(45deg, #00d4aa, #00f5ff);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
                transform: translateY(-2px);
            }

            .navbar-green .dropdown-menu {
                background: linear-gradient(135deg, #203a43, #2c5364);
                border: 1px solid rgba(0, 212, 170, 0.3);
                box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);
            }

            .navbar-green .dropdown-item {
                color: #fff !important;
                transition: all 0.3s ease;
            }

                .navbar-green .dropdown-item:hover {
                    background: linear-gradient(45deg, rgba(0, 212, 170, 0.2), rgba(0, 245, 255, 0.2));
                    color: #00f5ff !important;
                    transform: translateX(5px);
                }

        .navbar-toggler {
            border-color: rgba(0, 212, 170, 0.5);
        }

        .navbar-toggler-icon {
            background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='%2300f5ff' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
        }

        .container-fluid {
            background: transparent;
        }

        main {
            min-height: calc(100vh - 200px);
        }

        .footer {
            background: linear-gradient(135deg, #0f2027, #203a43);
            color: #fff;
            padding: 1.5rem 0;
            border-top: 2px solid rgba(0, 212, 170, 0.3);
            box-shadow: 0 -4px 20px rgba(0, 0, 0, 0.3);
        }

            .footer a {
                color: #00f5ff;
                text-decoration: none;
                transition: all 0.3s ease;
            }

                .footer a:hover {
                    color: #00d4aa;
                    text-decoration: underline;
                    transform: translateY(-2px);
                }

        /* Enhanced scrollbar styling */
        ::-webkit-scrollbar {
            width: 8px;
        }

        ::-webkit-scrollbar-track {
            background: #203a43;
        }

        ::-webkit-scrollbar-thumb {
            background: linear-gradient(45deg, #00d4aa, #00f5ff);
            border-radius: 4px;
        }

            ::-webkit-scrollbar-thumb:hover {
                background: linear-gradient(45deg, #00f5ff, #00d4aa);
            }

        /* Ensure content visibility on dark background */
        .card, .table, .form-control, .btn-outline-secondary {
            background: rgba(255, 255, 255, 0.95);
            color: #333;
            border: 1px solid rgba(0, 212, 170, 0.3);
        }

        .card {
            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);
        }

        .table {
            background: rgba(255, 255, 255, 0.98);
        }

        .btn-primary {
            background: linear-gradient(45deg, #00d4aa, #00f5ff);
            border: none;
            box-shadow: 0 4px 15px rgba(0, 212, 170, 0.3);
            transition: all 0.3s ease;
        }

            .btn-primary:hover {
                transform: translateY(-2px);
                box-shadow: 0 6px 20px rgba(0, 212, 170, 0.4);
            }

        .btn-success {
            background: linear-gradient(45deg, #00d4aa, #4ecdc4);
            border: none;
        }

        .btn-info {
            background: linear-gradient(45deg, #00f5ff, #48cae4);
            border: none;
        }

        .btn-warning {
            background: linear-gradient(45deg, #feca57, #ff9ff3);
            border: none;
        }

        .btn-danger {
            background: linear-gradient(45deg, #ff6b6b, #ee5a52);
            border: none;
        }

        /* Alert styling */
        .alert {
            border: 1px solid rgba(0, 212, 170, 0.3);
            background: rgba(255, 255, 255, 0.95);
        }

        .alert-success {
            border-color: #00d4aa;
            background: rgba(0, 212, 170, 0.1);
            color: #0f2027;
        }

        .alert-info {
            border-color: #00f5ff;
            background: rgba(0, 245, 255, 0.1);
            color: #0f2027;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-green border-bottom shadow-sm mb-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">InventoryManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain"
                        aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarMain">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="inventoryDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Inventory
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="inventoryDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Unit" asp-action="Index">Units</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Products</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Supplier" asp-action="Index">Suppliers</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Purchase" asp-action="Index">Purchases</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid p-0">
        <main role="main" class="pb-4">
            @RenderBody()
        </main>
    </div>

    <footer class="footer mt-auto">
        <div class="container text-center">
            &copy; 2025 - InventoryManager.WebUI -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>